### ISSUE TITLE
Recent plugin versions do not suport IntelliJ IDEA 2020.x (Important for Bazel users)

### ISSUE THREAD

**Issue by andrewhamon** [zio/zio-intellij#277]
From the readme:

> Supported versions: IntelliJ IDEA 2019.3, 2020.x, 2021.x (Community edition or better)

However, looking at the versions:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/5134584/121162467-efeeaa00-c81b-11eb-872c-8cee8a7438a6.png">

It appears that IntelliJ 2020.x support was dropped starting with version 2021.1.6.0.

I'm not sure if this was intentional or not.

This is problematic for the (admittedly very small) community of users that build their scala with bazel rather than sbt, since the bazel plugin only supports IntelliJ 2020.x currently. [They have an issue tracking 2021.x support](https://github.com/bazelbuild/intellij/issues/2406).

**Comment by hmemcpy** [comment]
Hello,

You raise a good point, but I think the IntelliJ website shows the year in which the update was released, not the version it's targeting. See the Scala plugin itself, for example:
![image](https://user-images.githubusercontent.com/601206/121168309-77a7d900-c85b-11eb-8c70-6814da5275e6.png)

Unfortunately, the plugin API changes between major releases (and sometimes between minor updates, although rare), and it's very hard to keep the plugin updated for all new versions. So I made a decision to drop support (i.e. adding new features) to the plugin once a new stable IntelliJ version is released. Currently I support 2020.3, 2021.1, and the upcoming 2021.2 is supported in early access. Unfortunately, due to time constraints and resources, once 2021.2 is released, I'll drop support for 2020.3 and will urge to upgrade.

Having said this, and having experienced bazel (lack of) support for the newest IntelliJ versions, I will be happy to fix and backport a specific issue if it occurs, or better yet - will take a pull request :) 

I have tags for all the older released versions, if you encounter an issue - you can fork off the tag and (hopefully) it still compiles (the build process depends on IntelliJ SDK versions being kept alive on their servers)

Hope this helps.

**Comment by hmemcpy** [comment]
Anyway, thank you again for the issue. I'm closing it for now. Please feel free to report any specific issues you may encounter with the bazel integration.

**Comment by andrewhamon** [comment]
> You raise a good point, but I think the IntelliJ website shows the year in which the update was released, not the version it's targeting.

I can confirm that on my instance of intellij 2020.3 I am unable to upgrade zio-intellij past version 2020.3.51, exactly as predicted by the version compatibility chart. So I think I am reading the chart correctly.

> Currently I support 2020.3, 2021.1, and the upcoming 2021.2 is supported in early access.

As of a few releases ago, you stopped supporting 2020.3. Perhaps that was inadvertent?

Anyways, its totally fine to drop support for older versions, but the readme should probably reflect that 🙂

**Comment by hmemcpy** [comment]
Hmm, I think you might be right re: supporting 2020.3... I must admit I had neglected that one a bit... Will try to backport some of the new changes to it.

Either way, you're also raising a good point about support: I will add a note on the readme about the support policy: two major versions (currently released + a previous release, e.g. 2021.1 and 2020.3)

**Comment by hmemcpy** [comment]
Actually, sorry, I take it back (it's late at night here, not thinking clearly).
The "two major releases" are for IntelliJ's "minor version". IntelliJ's latest released version is currently 2021.1.2, with the next major release 2021.2(.0) currently in EAP.

According to the support "policy", I will only support 2021.1.2 (current release) and 2021.1.1 (previous release). The 2020.3 support ended back in Feb.

So unfortunately, barring some critical bugs I won't be able to keep supporting 2020.3, but again - I'm happy to revisit this on a per-case basis. If some issue is preventing Bazel users from using the plugin correctly - I'd be happy to look into it.

**Comment by andrewhamon** [comment]
@hmemcpy it looks like the bazel plugin has published an early access version that supports 2021.1 just a few days ago, so with any luck, I should be able to upgrade to a newer version soon (or roll the dice with an unstable bazel plugin) 🙂 

I opened https://github.com/zio/zio-intellij/pull/280/files to update the readme (before I read your comments here, actually). Feel free to suggest changes or close it in favor of your own preferred edit.

**Comment by andrewhamon** [comment]
Also thanks a ton for responding so promptly, and for all the work you've put into the plugin!
